name: Windows - Advanced LiteManager Setup

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999  # Extended timeout for long-running processes
    
    steps:
      # Step 1: Downloading & Installing Essentials (LiteManager and other tools)
      - name: Downloading & Installing Essentials
        run: |
          # Download LiteManager and other essentials
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
          
          # Install Chocolatey (a Windows package manager)
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

          # Install monitoring tools and updates via Chocolatey
          choco install -y sysinternals # Sysinternals for system monitoring
          choco upgrade all -y          # Ensure everything is up to date

      # Step 2: Configuring Windows Firewall for LiteManager RDP Access
      - name: Configuring Windows Firewall
        run: |
          # Allow RDP and LiteManager in Firewall
          netsh advfirewall firewall add rule name="Allow RDP" protocol=TCP dir=in localport=3389 action=allow
          netsh advfirewall firewall add rule name="Allow LiteManager" protocol=TCP dir=in localport=5650 action=allow
          netsh advfirewall firewall add rule name="Allow LiteManager Viewer" protocol=TCP dir=in localport=5651 action=allow
          echo "Firewall configured for LiteManager and RDP"

      # Step 3: LiteManager Connection Setup
      - name: Connect to LiteManager
        run: |
          # Assuming the show.bat connects to LiteManager server
          cmd /c show.bat
          echo "LiteManager Connection Established"

      # Step 4: Monitoring and Logs
      - name: Install & Setup Monitoring Tools
        run: |
          # Install and run monitoring tools for system performance
          choco install -y procexp # Process Explorer from Sysinternals
          choco install -y processmonitor # Process Monitor for advanced monitoring
          
          # Run Process Monitor to capture system logs for diagnostics
          procmon /Minimized /Quiet /Backingfile procmon_log.pml
          echo "Process monitoring started and logs are being saved."

      # Step 5: Automated RDP Setup for Remote Access
      - name: Configure RDP for Remote Access
        run: |
          # Enable Remote Desktop access
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          
          # Set firewall rule for RDP (if not already enabled)
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389
          echo "RDP enabled and firewall configured."

      # Step 6: Time Counter to Monitor Execution Time
      - name: Time Counter
        run: |
          # Simple loop to count time or simulate time-based tasks
          cmd /c loop.bat
          echo "Time counting initiated for the task"

      # Step 7: System Cleanup or Optimization (Optional)
      - name: System Cleanup and Optimization
        run: |
          # Example cleanup task, could be temp file cleanup or optimizing disk usage
          cmd /c cleanmgr /sagerun:1
          echo "System cleanup performed"
